# используем режим обычного пользователя для сборки проекта.
sudo: false

language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database dream_job;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      a.s.kirson@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    CODECOV_TOKEN="f0b076ec-8a43-479c-aff9-c4bea997f035"